[build]
  command = "npm run build"
  publish = "app"  # Directorio principal de la aplicación Next.js

[functions.getTickets]
  path = "functions/getTickets.js"
  [functions.getTickets.environment]
    NODE_ENV = "production"

[functions.updateTickets]
  path = "functions/updateTickets.js"
  [functions.updateTickets.environment]
    NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
